- frontend/src/app/app-routing.module.ts
- frontend/src/app/app.module.ts
- frontend/src/app/core/services/auth.service.ts
- frontend/src/app/modules/auth/auth-routing.module.ts
- frontend/src/app/modules/main/main-routing.module.ts
- frontend/src/app/modules/user-profile/select-topics-page/select-topics-page.component.html
- frontend/src/app/modules/user-profile/user-profile-page/user-profile-page.component.html
- frontend/src/app/modules/user-profile/user-profile-routing.module.ts
- frontend/src/app/modules/user-profile/user-profile.module.ts
- Select topics component moved from user profile routing module to app routing module
- removed "main" from routes
- set default user profile path to profile/details
- set default auth path to auth/sign-in
- fixed static routes for redirects etc.
- set not found for wrong paths
> 65 Configured routing

- frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
- frontend/src/app/modules/lessons/lessons-page/lessons-page.component.sass
- frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
> 101 reworked lessons page so there are no empty space when questions opened

- frontend/src/app/shared/components/dropdown/dropdown.component.html
- frontend/src/app/shared/components/dropdown/dropdown.component.ts
- frontend/src/app/shared/components/interests-dropdown/interests-dropdown.component.html
- frontend/src/app/shared/components/interests-dropdown/interests-dropdown.component.ts
- frontend/src/app/shared/directives/click-outside.directive.ts
- frontend/src/app/shared/shared.module.ts
[As a user I want to close the filters by clicking anywhere on Timetable page, except the field with filter options](https://trello.com/c/BlJ0kDzS/98-as-a-user-i-want-to-close-the-filters-by-clicking-anywhere-on-timetable-page-except-the-field-with-filter-options)
> Close the filters by clicking anywhere on Timetable page, except the field with filter options

- frontend/src/app/modules/landing/landing-page/landing-page.component.html
- frontend/src/app/modules/landing/landing-page/landing-page.component.sass
[Fix moving the text to another line; increase space between text and images on AI field of Landing page](https://trello.com/c/jXK2qKVn/105-fix-moving-the-text-to-another-line-increase-space-between-text-and-images-on-ai-field-of-landing-page)
> fix ai section on landing page

- frontend/src/styles/index.sass
- frontend/src/styles/scrollbar.sass
> 108 added global custom scrollbar

- frontend/src/app/modules/auth/sign-in/sign-in.component.html
- frontend/src/app/modules/auth/sign-up/sign-up.component.html
- frontend/src/app/shared/directives/password-visibility.directive.ts
> 123 returned password visibility button, updated it's styles

- frontend/src/app/modules/user-card/user-card.component.html
- frontend/src/app/modules/user-card/user-card.component.sass
- frontend/src/app/modules/user-card/user-card.component.ts
> 162 - add user country flag on user card

- frontend/src/app/modules/auth/auth-page/auth-page.component.sass
- frontend/src/app/modules/auth/sign-in/sign-in.component.sass
- frontend/src/app/modules/auth/sign-up/sign-up.component.sass
> fixed a bug with error messages

- frontend/src/app/modules/chat/chat-page/chat-page.component.sass
- frontend/src/app/modules/chat/chat-page/chat-page.component.ts
- frontend/src/app/modules/chat/message-group/message-group.component.sass
1. Line on top
2. Time bottom margin
3. Message of other person
4. Left part to the bottom
5. Scroll distance on chat list
Other bugfix to finish today morning!!!
A little fixed max-width/min-width I can return it if it will necessary or edit
> some bugfix on chat page

- frontend/src/app/modules/lessons/lesson/lesson.component.sass
- frontend/src/app/modules/lessons/lessons-create/lessons-create.component.html
- frontend/src/app/modules/lessons/lessons-create/lessons-create.component.sass
- frontend/src/app/shared/components/interests-dropdown/interests-dropdown.component.sass
> 138 154 157 167 fixed all bugs related to create lesson component

- frontend/src/app/modules/filter-section/filter-section/filter-section.component.html
- frontend/src/app/modules/filter-section/filter-section/filter-section.component.ts
- frontend/src/app/modules/social-page/filter-section/filter-section.component.html
- frontend/src/app/modules/social-page/filter-section/filter-section.component.ts
- frontend/src/app/shared/components/dropdown/dropdown.component.html
- frontend/src/app/shared/components/dropdown/dropdown.component.sass
- frontend/src/app/shared/components/dropdown/dropdown.component.ts
> 158 full level name in level filter

- frontend/src/styles/scrollbar.sass
1 line pr, fixed scrollbar size
> 178 enormous scrollbar bugfix

- frontend/src/app/core/services/auth.service.ts
- frontend/src/app/modules/auth/sign-up/sign-up.component.ts
> fix user request

- frontend/src/app/modules/lessons/lesson/lesson.component.html
- frontend/src/app/modules/lessons/lesson/lesson.component.sass
> fixed bug with buttob and text location

- backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IUserService.cs
- backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/UserService.cs
- backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserDto.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Context/Seeder.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/User.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Migrations/20230403093042_AddedAdminStatusForUser.Designer.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Migrations/20230403093042_AddedAdminStatusForUser.cs
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/LessonsController.cs
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Controllers/UserController.cs
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
- frontend/src/app/core/services/auth.service.ts
- frontend/src/app/core/services/user.service.ts
- frontend/src/app/modules/lessons/lessons-page/lessons-page.component.html
- frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
- frontend/src/app/shared/models/IUserInfo.ts
Now we have admin flag in database. Only admin users can see "Create lesson" button and save lessons to database
> 95 isAdmin status

- backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/NewUserDto.cs
- backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserDto.cs
- backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/User/UserRegisterDto.cs
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Validators/User/NewUserDtoValidator.cs
- frontend/package.json
- frontend/src/app/modules/auth/sign-up/sign-up.component.html
- frontend/src/app/modules/auth/sign-up/sign-up.component.ts
- frontend/src/app/shared/components/calendar/calendar.component.html
- frontend/src/app/shared/components/calendar/calendar.component.sass
- frontend/src/app/shared/components/calendar/calendar.component.ts
- frontend/src/app/shared/models/INewUser.ts
- frontend/yarn.lock
> 125 176 saving private calendar

- frontend/src/app/modules/user-card/user-card.component.html
- frontend/src/app/modules/user-card/user-card.component.sass
- frontend/src/app/modules/user-card/user-card.component.ts
- frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.html
- frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.sass
- frontend/src/app/modules/user-profile/user-details/user-details/user-details.component.ts
- frontend/src/app/shared/components/avatar/avatar.component.html
- frontend/src/app/shared/components/avatar/avatar.component.sass
- frontend/src/app/shared/components/avatar/avatar.component.ts
- frontend/src/app/shared/components/header/header.component.html
- frontend/src/app/shared/components/header/header.component.sass
- frontend/src/app/shared/components/header/header.component.ts
If user has profile photo, it is shown on card on Social tab.
If user hasn’t profile photo, his initials with colored background has to be shown (look in header)
> 156 real user profile photo

- backend/EasySpeak.All.sln
- backend/EasySpeak.Core/EasySpeak.Core.BLL/EasySpeak.Core.BLL.csproj
- backend/EasySpeak.Core/EasySpeak.Core.BLL/Helpers/JwtHelper.cs
- backend/EasySpeak.Core/EasySpeak.Core.BLL/Interfaces/IZoomApiService.cs
- backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/LessonsService.cs
- backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/ZoomApiService.cs
- backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/LessonDto.cs
- backend/EasySpeak.Core/EasySpeak.Core.Common/DTO/Lesson/NewLessonDto.cs
- backend/EasySpeak.Core/EasySpeak.Core.Common/Exceptions/EasySpeakException.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/Lesson.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Entities/ZoomMeetingLinks.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Migrations/20230404140110_AddZoomLinkHostToLesson.Designer.cs
- backend/EasySpeak.Core/EasySpeak.Core.DAL/Migrations/20230404140110_AddZoomLinkHostToLesson.cs
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/EasySpeak.Core.WebAPI.csproj
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/Program.cs
- backend/EasySpeak.Core/EasySpeak.Core.WebAPI/appsettings.json
- backend/EasySpeak.Domain/EasySpeak.Domain.csproj
- backend/EasySpeak.Domain/Exceptions/EasySpeakException.cs
- frontend/src/app/models/lessons/lesson.ts
- frontend/src/app/modules/lessons/lessons-create/lessons-create.component.ts
- frontend/src/app/modules/lessons/lessons-page/lessons-page.component.ts
- frontend/src/app/shared/models/lesson/ILesson.ts
- frontend/src/app/shared/models/lesson/INewLesson.ts
This PR adds a feature to create Zoom meeting links for the lesson. Upon the creation of a lesson, **two** links will be generated: one for the **host** and one for the **students**.
> 116 Generate Zoom links

- frontend/src/app/modules/lessons/lesson/lesson.component.sass
> Fixed display of time on lesson card

- frontend/src/app/modules/forgot-password/change-password/change-password.component.ts
- frontend/src/app/modules/forgot-password/write-email/write-email.component.html
- frontend/src/app/modules/forgot-password/write-email/write-email.component.sass
- Now after password successfully reset, redirection to timetable
- Small visual changes accordind to design
> Fixed bug, and visual

- frontend/src/app/modules/forgot-password/write-email/write-email.component.html
- frontend/src/app/modules/forgot-password/write-email/write-email.component.sass
Visual changes to input field according to design
> 202-forgot-password-page-button

- backend/EasySpeak.Core/EasySpeak.Core.BLL/Services/NotificationService.cs
- frontend/src/app/shared/components/user-notification/user-notification.component.html
- frontend/src/app/shared/components/user-notification/user-notification.component.ts
Hide MarkAsRead if there are no unread notifications
Renew notification badge when click mark as read
Get from BE only unread notifications
> 220 Hide "Mark as read" button in notifications

- frontend/src/app/modules/auth/sign-in/sign-in.component.html
- frontend/src/app/modules/auth/sign-in/sign-in.component.sass
[As a user I want to have Forgot password button on Login page](https://trello.com/c/Ap5YDgR9/245-as-a-user-i-want-to-have-forgot-password-button-on-login-page)
> Add 'Forgot password' on Sign in page

- frontend/src/app/modules/user-card/user-card.component.html
> 122 the design of cards

- backend/EasySpeak.RecommendationService/Dockerfile
- docker-compose.apps.prod.yml
- docker-compose.apps.yml
- Fixed RecommendationService dockerfile configurations
- Fixed dependencies inside compose files
> Fixed docker compose files and recommendator service's dockerfile
